### ISSUE TITLE
Any plans to update to recent jsdom and nodejs?

### ISSUE THREAD

**Issue by rjmackay** [saymedia/angularjs-server#31]
Are there any plans to update this module to more recent version of nodejs and jsdom?

**Comment by thrashr888** [comment]
I've been looking at this myself but haven't had much time. We'd like to since this is blocking us from moving to Node v4+. We have a project downstream from this lib that we'd like to upgrade but we're okay with it not working with the latest version of this lib until we get to it.

We need to update the underlying `angularcontext` lib first, which it looks like you've sent a PR for (thanks!). Once that gets through we can upgrade this lib.

**Comment by thrashr888** [comment]
`angularcontext` has been updated. I'm looking at upgrading the dependency now. It passes tests but I'd like to poke at it some more.

**Comment by thrashr888** [comment]
Done!
